### ISSUE TITLE
Get taxonomy by slug

### ISSUE THREAD

**Issue by PanMan** [kadamwhite/wordpress-rest-api#95]
In the docs (frontpage) it says:

    wp.taxonomies().taxonomy( 'taxonomy_name' ).term( termIdentifier ): get the term with slug or ID termIdentifier from the taxonomy taxonomy_name

This works with the ID, but not with the slug :(. Is this something that changed?

HOST/wp-json/taxonomies/post_tag/terms/42 works
HOST/wp-json/taxonomies/post_tag/terms/sociaal-ondernemerschap doesn't

**Comment by kadamwhite** [comment]
In the intervening year, this has been broken again by the v2 beta upgrades: WP-API/WP-API#924 identifies that `filter` is not currently supported on the `/categories` or `/tags` endpoints.

WP-API/WP-API#2065 has been opened to identify whether this will ever be reinstated; in the mean time, #126 will add a demonstration of using the `?search` parameter to _slightly_ more efficiently retrieve a specific term by slug (basically the same "get them all and search for the one you want in the response" approach detailed above, but with less overhead due to the narrowing effect of `?search=the-slug`).

**Comment by kadamwhite** [comment]
The "slug" query parameter is now supported by the WordPress REST API for the `tags` and `categories` endpoints. https://github.com/WP-API/WP-API/issues/924
